<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<LangVersion>10</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Properties\**" />
	  <EmbeddedResource Remove="Properties\**" />
	  <None Remove="Properties\**" />
	  <Page Remove="Properties\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="App.config" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FoundationR\FoundationR.csproj" />
	</ItemGroup>

</Project>